### ISSUE TITLE
Issue with GitHub Container Registry (GHCR) URL Case Sensitivity

### ISSUE THREAD

**Issue by ThijmenGThN** [rafalkk/remove-dockertag-action#1]
Hi there,

I recently attempted to implement your workflow, which I find quite promising. However, I encountered an issue due to the case sensitivity of GitHub usernames in GHCR URLs. My GitHub username is capitalized, but unfortunately, GHCR only supports lowercase URLs.

Is there a possibility for this to be resolved in the near future?

Here are the details of the encountered problem. If you need more information, I'm more than willing to provide additional logs. You can also find the exact workflow run at the following link: [Workflow Run](https://github.com/ThijmenGThN/swaparr/actions/runs/8389085923/job/22974570427)

Error Message:

```
Error: buildx failed with: ERROR: invalid tag "ghcr.io/ThijmenGThN/swaparr:edge": repository name must be lowercase
```

Workflow yaml:

```yml
name: Publish to GitHub Container Registry

on:
  push:
    branches: [edge]

jobs:
  recycle:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Recycle Edge Image
      uses: rafalkk/remove-dockertag-action@v1
      with:
        tag_name: edge
        github_token: ${{ secrets.GH_PAT }}
```
